spring.application.name=pos-service
spring.datasource.url=jdbc:postgresql://157.10.161.207:5432/nivora-pos-db
spring.datasource.username=postgres
spring.datasource.password=ShaninHanan23
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Jakarta
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true
spring.jpa.properties.hibernate.query.plan_cache_max_size=2048
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.jackson.time-zone=Asia/Jakarta
jwt.secret=NivoraPOSSecretKey2024VeryLongSecretForHS256Algorithm
jwt.expiration=86400000
server.servlet.context-path=/NivoraPos
security.preauthorize.enabled=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload.dir=uploads/images
app.upload.public-base-url=
app.upload.max-size-bytes=5242880
psgs.integration.enabled=true
psgs.datasource.url=jdbc:mysql://localhost:3306/midware_master?useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta
psgs.datasource.username=root
psgs.datasource.password=123456
psgs.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
psgs.datasource.master-schema=midware_master
psgs.login.require-password=false
